export const EXAMPLE_CHANGE_TITLE = 'EXAMPLE_CHANGE_TITLE';

export const LOAD_ANIMAL = 'LOAD_ANIMAL';
export const LOAD_ANIMAL_SUCCESS = 'LOAD_ANIMAL_SUCCESS';
export const LOAD_ANIMAL_FAIL = 'LOAD_ANIMAL_FAIL';
