export const EXAMPLE_CHANGE_TITLE_APPS = 'EXAMPLE_CHANGE_TITLE_APPS';

export const LOAD_ANIMAL_APPS = 'LOAD_ANIMAL_APPS';
export const LOAD_ANIMAL_SUCCESS_APPS = 'LOAD_ANIMAL_SUCCESS_APPS';
export const LOAD_ANIMAL_FAIL_APPS = 'LOAD_ANIMAL_FAIL_APPS';
